language: node_js
node_js:
  - "iojs"
  - "7"

env:
  global:
    - "FTP_USER=pi"
    - "FTP_PASSWORD=tjdals86"
after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://zzing.co.kr/var/www/html/drz"