language: php
php:
  - 5.5
branches:
  only:
    - develop
env:
  global:
    - "FTP_USER=pi"
    - "FTP_PASSWORD=tjdals86"
before_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://zzing.co.kr/var/www/html/drz"